apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ryas
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jcmm-tenant/rhtap-demo-app/hacbs-test-project-ryas@sha256:467211762807c9ad7707f7642870f00bef72daa073b8471cad3eae284cf1fe25
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
