apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ryas
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ryas
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ryas
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ryas
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ryas
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jcmm-tenant/rhtap-demo-app/hacbs-test-project-ryas@sha256:467211762807c9ad7707f7642870f00bef72daa073b8471cad3eae284cf1fe25
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
